version: "3.3"

services:
    rt_apache:
        build:
          context: apache
        ports:
            - "8080:80"
        volumes:
            - "../:/var/www/html/:delegated"

    rt_php7.4:
        build:
          context: php7.4
        volumes:
            - "../:/var/www/:delegated"
        environment:
            - APP_ENV=dev
            - APP_DEBUG=true
            - DATABASE_URL=mysql://root:root@rt_db/radioteboulba
    rt_db:
        build:
            context: mysql
        command: --default-authentication-plugin=mysql_native_password --sql_mode=""
        ports:
            - "3306:3306"
        restart: always
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=radioteboulba
